version: '3.9'
services:
  centromedico:
    build:
      context: ./centro_medico
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      APP_ENV: "production"
      APP_DEBUG: "false"
      APP_URL: "http://34.60.43.34:8080"
      DB_HOST: "34.28.82.88"
      DB_DATABASE: "ixocakuy_medisys"
      DB_USERNAME: "root"
      DB_PASSWORD: "Medisys123"
      MICROSERVICIO_RENIEC_URL: "http://microservicio_reniec:8001/api/reniec/dni"
    depends_on:
      - microservicio_reniec

  microservicio_reniec:
    build:
      context: ./microservicio_reniec
      dockerfile: Dockerfile
    ports:
      - "8002:8001"
    environment:
      APP_ENV: "production"
      APP_DEBUG: "false"
      APP_URL: "http://34.60.43.34:8002"
      DB_HOST: "34.28.82.88"
      DB_DATABASE: "ixocakuy_medisys"
      DB_USERNAME: "root"
      DB_PASSWORD: "Medisys123"
      RENIEC_BASE_URL: "https://api.apis.net.pe/v2/reniec"
      RENIEC_TOKEN: "apis-token-12231.7uDBmK5QAsQVvDrgWnpyH3g23czkS7du"